### ISSUE TITLE
Add "OnAddressRead" / "OnAddressWrite" events to LuaEngine

### ISSUE THREAD

**Issue by tommadness** [Topaz-Reality/PCSX2-EX#1]
When developing LUA scripts, I have a need to execute a LUA function when the game reads from a particular address or from a block of addresses.

**Comment by Topaz-Reality** [comment]
I have looked into this with a couple of people who have modified PCSX2 (Thanks kkdf2) but unfortunately, since the addresses are determined dynamically on function, we cannot see when a specific address is being accessed.

Sorry for the inconvenience, I tried everything to make this work but at this moment it is not possible. You can still write a function to monitor when the address changes values, but not when it's being accessed.

Issue closed.
